name: 'QACommerce - CI'

# Triggers
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run tests daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    
    env:
      CYPRESS_baseUrl: http://localhost:3000
      CYPRESS_video: false
      CYPRESS_screenshotOnRunFailure: true
    
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
      
      - name: Instalar dependências
        run: npm install
      
      - name: Iniciar o servidor da aplicação
        run: |
          npm run serve &
          npx wait-on http://localhost:3000 --timeout 30000
      
      - name: Executar os testes Cypress
        run: npx cypress run
      
      - name: Upload dos screenshots (se falhar)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          retention-days: 7